### ISSUE TITLE
Exoflex

### ISSUE THREAD

**Issue by oshimayoan** [kodefox/infra#3]
To provide tooling and components to increase speed and ease of building production quality UI on React Native, both mobile and web.

## Goal
- Provide a set of UI components that can adapt to many different UI designs with minimal effort.
- Sensible defaults so that only minimal configuration is required.
- Abstract font loading, font styles, and other text properties so that it’s easy to define in one place the typefaces for an entire application.
- Use Hooks rather than classes or HoC
- Usable on both React Native and RN Web
- Full TypeScript support out of the box

## Todos
- [x] Font Loading and configuration (#4)
- [ ] Drawer
- [ ] Carousel
- [ ] Slider Selection
- [ ] Wrapping react-native-paper
- [ ] Calendar with Multiple Date Select (Range) Supports (#13)
